// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pnefapjkqlvjxgvgklci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBuZWZhcGprcWx2anhndmdrbGNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTc1NzEsImV4cCI6MjA2NTU3MzU3MX0.mBsRbiK5yQSf4j6CR9-1GBe-OzPFxNsU6J9ZBbjKvTQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);